---

- name: instalando dependencias do docker
  hosts: docker
  remote_user: root
  tasks:
    - name: instalando o python-pip
      apt:
       name: python-pip
    - name: instalando a dependencia para o docker
      pip:
       name: docker-py
    - name: instalando o docker
      apt:
       name: docker
       state: present 
